# Generated by Django 5.1.6 on 2025-03-18 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CastMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("ACTOR", "ACTOR"), ("DIRECTOR", "DIRECTOR")],
                        max_length=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cast Member",
                "verbose_name_plural": "Cast Members",
                "db_table": "cast_member",
            },
        ),
    ]
