# Generated by Django 5.1.6 on 2025-03-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
