# Generated by Django 5.1.7 on 2025-04-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0002_alter_video_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiovideomedia",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[("TRAILER", "TRAILER"), ("VIDEO", "VIDEO")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="imagemedia",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BANNER", "BANNER"),
                    ("THUMBNAIL", "THUMBNAIL"),
                    ("THUMBNAIL_HALF", "THUMBNAIL_HALF"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
