# Generated by Django 5.1.7 on 2025-04-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0003_audiovideomedia_media_type_imagemedia_image_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiovideomedia",
            name="media_type",
            field=models.CharField(
                choices=[("TRAILER", "TRAILER"), ("VIDEO", "VIDEO")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="imagemedia",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("BANNER", "BANNER"),
                    ("THUMBNAIL", "THUMBNAIL"),
                    ("THUMBNAIL_HALF", "THUMBNAIL_HALF"),
                ],
                max_length=15,
            ),
        ),
    ]
