# Generated by Django 5.1.6 on 2025-03-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genre_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="genre",
            table="genre",
        ),
    ]
